    name: Deploy to Production
    
    on:
      push:
        branches:
          - master
    
    jobs:
      deploy:
        name: Build, Deploy to S3 bucket
        runs-on: [ubuntu-latest]
    
        strategy:
          matrix:
            node-version: [v18.12.1]
    
        steps:
          - uses: actions/checkout@v2
    
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
              node-version: ${{ matrix.node-version }}
    
          - name: Npm install
            run: npm install
            
          - name: env inject
            env: 
                DATABASE_URL: ${{secrets.DATABASE_URL}}
                ACCESS_KEY_ID: ${{secrets.ACCESS_KEY_ID}}
                SECRET_ACCESS_KEY: ${{secrets.SECRET_ACCESS_KEY}}
                REGION: ${{secrets.REGION}}
                SIGNATUREVERSION: ${{secrets.SIGNATUREVERSION}}
                MY_SECRET_KEY: ${{secrets.MY_SECRET_KEY}}
                ACCESS_TOKEN_EXPIRES: ${{secrets.ACCESS_TOKEN_EXPIRES}}
                RERESH_TOKEN_EXPIRES: ${{secrets.RERESH_TOKEN_EXPIRES}}
    
          - name: Build
            run: npm run build
    
          - name: Transfer to S3 for serving static
            uses: jakejarvis/s3-sync-action@master
            with:
              args: --acl public-read --follow-symlinks --delete
            env:
              AWS_S3_BUCKET: growing-server-deployment
              AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER_ACCESS_KEY }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER_SECRET_KEY }}
              AWS_REGION: ap-northeast-2
              SOURCE_DIR: 'dist'
